name: Build Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 添加 gradlew 权限
        run: chmod +x gradlew

      - name: 开始构建
        run: ./gradlew build

      - name: 上传构建文件
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: build/libs/
